spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:

  jpa:
    #show-sql: false
    #generate-ddl: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      #properties:
      #show_sql: true
      #format_sql: true
      show_comment: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: true

decorator:
  datasource:
    p6spy:
      multiline: true
      enable-logging: true
    #logging.level:
    #org.hibernate.SQL: debug
    #org.type.descriptor.sql.BasicBinder: TRACE

